declare const IS_PROD: boolean;
declare const FLOW_ACCESS_URL: string;
declare const DISCOVERY_WALLET: string;
declare const FUNGIBLE_TOKEN_ADDRESS: string;
declare const NONFUNGIBLE_TOKEN_ADDRESS: string;
declare const FLOW_TOKEN_ADDRESS: string;
declare const METADATA_ADDRESS: string;
declare const STOREFRONT_ADDRESS: string;
declare const KARTINAITEMS_ADDRESS: string;
